USE vananta_db;

TRUNCATE TABLE services;

INSERT INTO services (title, title_en, description, description_en, icon_class) VALUES
('Doctor Home Visit', 'Doctor Home Visit', 'Konsultasi medis, pemeriksaan, dan pengobatan profesional yang diberikan langsung di rumah Anda oleh dokter bersertifikat.', 'Professional medical consultations, examinations, and treatments delivered directly to your home by certified physicians.', 'fa-solid fa-user-doctor'),
('Home Vaccination & Infusion Therapy', 'Home Vaccination & Infusion Therapy', 'Layanan vaksinasi dan infus vitamin yang dilakukan dengan protokol medis ketat untuk mendukung imunitas, pemulihan, dan kesehatan secara keseluruhan.<br>Termasuk: &bull; Vaksinasi preventif &bull; Infus vitamin &bull; Terapi cairan', 'Vaccination and vitamin infusion services conducted under strict medical protocols to support immunity, recovery, and overall wellness.<br>Includes: &bull; Preventive vaccination &bull; Vitamin infusion &bull; Fluid therapy', 'fa-solid fa-syringe'),
('Elderly & Long-Term Care', 'Elderly & Long-Term Care', 'Perawatan komprehensif dan penuh kasih sayang untuk pasien lansia, berfokus pada bantuan harian, pemantauan medis, dan kualitas hidup.', 'Comprehensive and compassionate care for elderly patients, focusing on daily assistance, medical monitoring, and quality of life.', 'fa-solid fa-hands-holding-child'),
('Home Laboratory Service', 'Home Laboratory Service', 'Pengambilan sampel laboratorium yang nyaman dan akurat di rumah tanpa perlu kunjungan ke rumah sakit atau waktu tunggu.', 'Convenient and accurate laboratory sample collection at home without the need for hospital visits or waiting time.', 'fa-solid fa-flask'),
('Medical Evacuation & Emergency Support', 'Medical Evacuation & Emergency Support', 'Layanan evakuasi medis yang aman dan terkoordinasi dengan dukungan tim terlatih dan peralatan darurat yang lengkap.', 'Safe and coordinated medical evacuation services supported by trained teams and complete emergency equipment.', 'fa-solid fa-truck-medical'),
('Palliative Care', 'Palliative Care', 'Dukungan holistik secara fisik, emosional, dan psikologis untuk pasien dengan kondisi kronis dan membatasi hidup, yang diberikan dengan martabat dan empati.', 'Holistic physical, emotional, and psychological support for patients with chronic and life-limiting conditions, delivered with dignity and empathy.', 'fa-solid fa-heart-pulse'),
('Medical Support for Events', 'Medical Support for Events', 'Layanan medis profesional di tempat untuk acara perusahaan, publik, dan pribadi guna memastikan keselamatan peserta dan respons darurat yang cepat.', 'Professional on-site medical services for corporate, public, and private events to ensure participant safety and rapid emergency response.', 'fa-solid fa-kit-medical');
